[tools]
"cargo:cargo-audit" = "0.21.2"
"cargo:cargo-deny" = "0.18.4"
"cargo:cargo-hack" = "0.6.38"
"cargo:cargo-insta" = "1.43.2"
"cargo:cargo-llvm-cov" = "0.6.19"
"cargo:cargo-msrv" = "0.18.4"
"cargo:cargo-nextest" = "0.9.103"
"cargo:cargo-outdated" = "0.17.0"
"cargo:cargo-watch" = "8.5.3"
"cargo:cbindgen" = "0.29.0"
"cargo:leptosfmt" = "0.1.33"
"cargo:trunk" = "0.21.14"
"cargo:wasm-bindgen-cli" = "0.2.101"
"cargo:wasm-pack" = "0.13.1"
"go:github.com/google/addlicense" = "1.2.0"
"npm:markdownlint-cli2" = "latest"
"ubi:https://github.com/WebAssembly/wabt/releases/tag/1.0.37" = "latest"

# Build tools
actionlint = "latest"
cargo-binstall = "1.15.4"
fd = "10.3.0"
go = "prefix:1.25"
golangci-lint = "2.4.0"
jq = "1.8.1"
just = "1.42.4"
node = "24.7.0"
pnpm = "10.15.1"
pre-commit = "4.3.0"
python = "prefix:3.12"
"rust" = { version = "prefix:1.89", targets = "wasm32-unknown-unknown" }
uv = "0.8.15"

[env]
COREPACK_ENABLE_DOWNLOAD_PROMPT = "1"
LIBRARY_PATH = "$LIBRARY_PATH:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib:/opt/homebrew/opt/libiconv/lib"
MACOSX_DEPLOYMENT_TARGET = "11.0"
RUST_BACKTRACE = "1"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]
