#!/usr/bin/env bash
#MISE description="Build Go bindings"
set -euo pipefail

mise run go:generate-bindings
mise run rust:build

source "${MISE_PROJECT_ROOT}/scripts/tasks/go-env.sh"
cd "${MISE_PROJECT_ROOT}/crates/go/go"
go build ./...
