#!/usr/bin/env bash
#MISE description="Generate HTML and LCOV coverage reports"
set -euo pipefail

export CARGO_TARGET_DIR="${MISE_PROJECT_ROOT}/target/llvm-cov-target"

mise run rust:test-coverage
cargo llvm-cov report --html
cargo llvm-cov report --lcov --output-path lcov.info
