#!/usr/bin/env bash
#MISE description="Watch Rust sources for changes"
set -euo pipefail

cargo watch -x 'check --workspace --all-targets --all-features' -x 'nextest run --workspace --all-features --no-fail-fast'
