#!/usr/bin/env bash
#MISE description="Watch Rust sources for changes"
set -euo pipefail

cargo watch -x 'check --workspace --all-targets --all-features' -s "${MISE_PROJECT_ROOT}/mise-tasks/rust/test"
