name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  full:
    name: Full Configuration
    uses: ./.github/workflows/ci-steps.yml
    with:
      wasm: true
      python: true
      go: true
      cache_suffix: "full"

  matrix:
    name: Matrix Configurations
    needs: full
    strategy:
      matrix:
        config:
          - { wasm: true,  python: false, go: false, cache_suffix: "no-py" }
          - { wasm: false, python: true,  go: false, cache_suffix: "no-wasm" }
          - { wasm: false, python: false, go: false, cache_suffix: "minimal" }
          - { wasm: false, python: false, go: true,  cache_suffix: "go-only" }
    uses: ./.github/workflows/ci-steps.yml
    with:
      wasm: ${{ matrix.config.wasm }}
      python: ${{ matrix.config.python }}
      go: ${{ matrix.config.go }}
      cache_suffix: ${{ matrix.config.cache_suffix }}
